export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_ERROR = 'PRODUCT_LIST_ERROR';

export const PRODUCT_ITEM_REQUEST = 'PRODUCT_ITEM_REQUEST';
export const PRODUCT_ITEM_SUCCESS = 'PRODUCT_ITEM_SUCCESS';
export const PRODUCT_ITEM_ERROR = 'PRODUCT_ITEM_ERROR';
